### ISSUE TITLE
1.md：文中的“智能体”是一种术语么？如果不是的话，是否可以翻译成更恰当的词？

### ISSUE THREAD

**Issue by nirui** [Kivy-CN/think-comp-2e-zh#4]
看了下原文，对应的应该是“agents”。感觉翻译成“智能体”之后，反而让文章更加难理解了。

请考虑一下。

**Comment by wizardforcel** [comment]
是的。

**Comment by ThinkLoudly** [comment]
其实代理人和智能体都可以，但是代理人好像在台湾的语境下用的更多，大陆用智能体比较多

参考[https://zhuanlan.zhihu.com/p/26120297](https://zhuanlan.zhihu.com/p/26120297)
