### ISSUE TITLE
建议使用国产翻译工具辅助翻译

### ISSUE THREAD

**Issue by ThinkLoudly** [Kivy-CN/think-comp-2e-zh#5]
主要是因为Google翻译效果近几年都没有进步，我认为使用国产翻译工具的话需要修饰的地方更少，大幅提升可读性和翻译效率，我们可以对比一下。

因为英文原版和译者的中文版有些对不上号，猜测是版本不同（比如原文第一章中没有提到Stephen Wolfram）所以我就选一段内容差异不是很大的段落做对比。

没有点出国产翻译工具的名字是因为基本上主流的那几个翻译工具效果也差不了多少，译者可以体验一下。

英文原文：

> Let me contrast that with a different kind of explanation. Suppose you move to a city like Detroit that is racially segregated, and you want to know why it’s like that. If you do some research, you might find a paper by Thomas Schelling called “Dynamic Models of Segregation”, which proposes a simple model of racial segregation:
> The Schelling model of the city is an array of cells where each cell represents a house. The houses are occupied by two kinds of “agents”, labeled red and blue, in roughly equal numbers. About 10% of the houses are empty.

译者翻译：
> 让我用另一种解释来对比一下。假设你搬到像底特律这样种族隔离的城市，你想知道为什么这样。如果你做一些研究，你可能会发现 Thomas Schelling 的一篇文章，称为“分离动态模型”，它提出了一个简单的种族隔离模型：
> 城市的谢林模型是一个单元格数组，每个单元格代表一个房子。这些房子被两种“智能体”占据，标有红色和蓝色，数量大致相等。大约10％的房子是空的。

Google Translate：
> 让我用另一种解释来对比。 假设你转移到像种族隔离的底特律这样的城市，你想知道为什么它是这样的。 如果你做了一些研究，你可能会发现托马斯谢林的一篇名为“动态隔离模型”的文章，它提出了一个简单的种族隔离模型：
> 城市的Schelling模型是一组单元格，每个单元格代表一栋房屋。 房屋被两种“代理人”占据，标记为红色和蓝色，数量大致相同。 大约10％的房屋是空的。

某国产翻译工具：
> 让我用一种不同的解释来对比一下。 假设你搬到像底特律这样种族隔离的城市, 你想知道为什么会这样。 如果你做一些研究, 你可能会发现一篇名为《种族隔离动态模型》(Dynamic Models of Segregation)的论文, 其中提出了一个简单的种族隔离模式:
> 这座城市的谢林模型是一系列的细胞, 每个细胞代表一座房子。 这些房子被两种"代理人"占据, 标有红色和蓝色, 数量大致相等。 大约10% 的房子是空的

另一国产翻译工具：
> 让我用另一种解释来对比一下。假设你搬到底特律这样一个种族隔离的城市，你想知道为什么会这样。如果你做一些研究，你可能会发现托马斯·谢林的一篇论文叫做“种族隔离的动态模型”，它提出了一个简单的种族隔离模式:
> 城市的谢林模型是一组细胞，每个细胞代表一所房子。房子里有两种“代理人”，分别是红色和蓝色，数量大致相等。大约10%的房子是空的。

**Comment by cycleuser** [comment]
我更建议人工翻译，我不认为短期内这些机器翻译能够达到令人满意的翻译质量。

**Comment by wizardforcel** [comment]
@cycleuser 我时间那么宝贵怎么可能人工翻译 -____-

**Comment by cycleuser** [comment]
也对，如果先机翻，然后大家人工校正，可能也是一个好思路~
